version: "3"
services:
  redmine:
    container_name: redmine_mytheme
    image: redmine:4.2.2-passenger
    restart: always
    ports:
      - 8080:3000
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_DATABASE: redmine_mytheme
      REDMINE_DB_USERNAME: redmine_mytheme
      REDMINE_DB_PASSWORD: redmine_mytheme
      REDMINE_DB_ENCODING: utf8mb4
    depends_on:
      - mysql
    volumes:
      - ./src/assets:/usr/src/redmine/public/themes/mytheme
  mysql:
    container_name: mysql_mytheme
    image: mysql:8.0
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: redmine_mytheme
      MYSQL_USER: redmine_mytheme
      MYSQL_PASSWORD: redmine_mytheme
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
